[package]
name = "cute-ledger"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
csv = "1.3.1"
rust_decimal = "1.37.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
thiserror = "2.0.12"
